version: '3'

services:
  instance:
    build:
      context: /data/hoyolab-auto/
      dockerfile: Dockerfile
    restart: on-failure:5
    container_name: hoyolab-auto
    network_mode: bridge
    volumes:
      - /data/hoyolab-auto/config.json5:/app/config.json5:ro
      - data:/app/data
    environment:
      TZ: Asia/Shanghai

volumes:
  config:
  data:
