version: '3'

services:
  mc:
    image: itzg/minecraft-server:${IMAGE_TAG:-latest}
    volumes:
      - /data/minecraft-prominence2:/data
      - /data/minecraft/modpacks:/modpacks:ro
    environment:
      EULA: "true"
      MOD_PLATFORM: AUTO_CURSEFORGE
      DEBUG: "${DEBUG:-false}"
      CF_API_KEY: ${CF_API_KEY}
      CF_SLUG: prominence-2-rpg
      CURSEFORGE_FILES: luna
      CF_FORCE_SYNCHRONIZE: true
      INIT_MEMORY: 8G
      MAX_MEMORY: 16G
      USE_AIKAR_FLAGS: true
      MOTD: Running %MODPACK_NAME% version %env:MODPACK_VERSION%
      LEVEL: prominence2-world
      RCON_PASSWORD: ${RCON_PASSWORD}
      RCON_CMDS_STARTUP:  |-
        /gamerule doFireTick false
      RCON_CMDS_FIRST_CONNECT: |-
        /pregen stop
      RCON_CMDS_LAST_DISCONNECT: |-
        /kill @e[type=minecraft:boat]
    ports:
      - "25565:25565"
      - "127.0.0.1:25575:25575"

volumes:
  data: {}