services:
  mc:
    image: itzg/minecraft-server:${IMAGE_TAG:-latest}
    container_name: minecraft-prominence2
    volumes:
      - minecraft_prominence2_data:/data
    environment:
      EULA: "true"
      MOD_PLATFORM: AUTO_CURSEFORGE
      DEBUG: "${DEBUG:-false}"
      CF_API_KEY: ${CF_API_KEY}
      CF_SLUG: prominence-2-rpg
      #CURSEFORGE_FILES: luna, textile-backup, cloth-config, modmenu, fancymenu
      CURSEFORGE_FILES: modmenu, fancymenu
      INIT_MEMORY: 8G
      MAX_MEMORY: 24G
      USE_AIKAR_FLAGS: true
      MOTD: Running %MODPACK_NAME% version %env:MODPACK_VERSION%
      LEVEL: prominence2-world
      LEVEL_TYPE: minecraft:large_biomes
      RCON_PASSWORD: ${RCON_PASSWORD}
      CUSTOM_SERVER_PROPERTIES: |-
        allow-flight=true
        spawn-protection=false
      RCON_CMDS_STARTUP:  |-
        /gamerule doFireTick false
        /gamerule mobGriefing false
      #RCON_CMDS_FIRST_CONNECT:
      #RCON_CMDS_LAST_DISCONNECT:
    ports:
      - "25565:25565"
      - "127.0.0.1:25575:25575"
    networks:
      - minecraft_network
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 24G
        reservations:
          memory: 8G
    healthcheck:
      test: ["CMD", "mc-status", "--host", "localhost"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 120s
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    labels:
      - "com.docker.compose.project=games"
      - "com.docker.compose.service=minecraft-prominence2"
    restart: unless-stopped

  mc-backup:
    image: itzg/mc-backup
    container_name: minecraft-prominence2-backup
    depends_on:
      - mc
    environment:
      BACKUP_INTERVAL: "2h"
      PRUNE_BACKUPS_DAYS: "7"
      PRUNE_RESTIC_RETENTION: "--keep-daily 7 --keep-weekly 4 --keep-monthly 12"
      BACKUP_METHOD: "restic"
      RESTIC_REPOSITORY: "/backup/minecraft/minecraft-prominence2"
      RESTIC_PASSWORD: ${RESTIC_PASSWORD:-minecraft-backup-password}
      RCON_HOST: mc
      RCON_PORT: 25575
      RCON_PASSWORD: ${RCON_PASSWORD}
      PAUSE_IF_NO_PLAYERS: "true"
      EXCLUDES: "*.jar,cache,logs"
    volumes:
      - minecraft_prominence2_data:/data:ro
      - minecraft_prominence2_backups:/backup/minecraft/minecraft-prominence2
    networks:
      - minecraft_network
    labels:
      - "com.docker.compose.project=games"
      - "com.docker.compose.service=minecraft-prominence2-backup"
    restart: unless-stopped

networks:
  minecraft_network:
    driver: bridge

volumes:
  minecraft_prominence2_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/minecraft-prominence2
  minecraft_prominence2_backups:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /backup/minecraft/minecraft-prominence2