version: '3'

services:
  mc:
    image: itzg/minecraft-server:${IMAGE_TAG:-latest}
    volumes:
      - /data/minecraft-prominence2:/data
      - /data/minecraft/modpacks:/modpacks:ro
    environment:
      EULA: "true"
      MOD_PLATFORM: AUTO_CURSEFORGE
      DEBUG: "${DEBUG:-false}"
      CF_API_KEY: ${CF_API_KEY}
      CF_SLUG: prominence-2-rpg
      CURSEFORGE_FILES: luna, chunky-pregenerator, textile-backup, cloth-config, modmenu, fancymenu
      INIT_MEMORY: 8G
      MAX_MEMORY: 24G
      USE_AIKAR_FLAGS: true
      MOTD: Running %MODPACK_NAME% version %env:MODPACK_VERSION%
      LEVEL: prominence2-world
      LEVEL_TYPE: minecraft:large_biomes
      RCON_PASSWORD: ${RCON_PASSWORD}
      CUSTOM_SERVER_PROPERTIES: |-
        allow-flight=true
        spawn-protection=false
      RCON_CMDS_STARTUP:  |-
        /gamerule doFireTick false
        /gamerule mobGriefing false
      #RCON_CMDS_FIRST_CONNECT:
      #RCON_CMDS_LAST_DISCONNECT:
    ports:
      - "25565:25565"
      - "127.0.0.1:25575:25575"
volumes:
  data: {}