version: '3'

services:
  mc:
    image: itzg/minecraft-server:${IMAGE_TAG:-latest}
    volumes:
      - /data/minecraft-steampunk:/data
      - /data/minecraft/modpacks:/modpacks:ro
    environment:
      EULA: "true"
      MOD_PLATFORM: AUTO_CURSEFORGE
      DEBUG: "${DEBUG:-false}"
      VERSION: ${VERSION:-1.19.2}
      CF_API_KEY: ${CF_API_KEY}
      FORGE_VERSION: ${FORGE_VERSION:-43.4.0}
      CF_SLUG: steam-punk
      CURSEFORGE_FILES: https://www.curseforge.com/minecraft/mc-mods/ftb-backups-2/files/4834398
      INIT_MEMORY: 8G
      MAX_MEMORY: 16G
      USE_AIKAR_FLAGS: true
      MOTD: Running %MODPACK_NAME% version %env:MODPACK_VERSION%
      LEVEL: world
      RCON_PASSWORD: ${RCON_PASSWORD}
      RCON_CMDS_STARTUP:  |-
        /pregen start 200
        /gamerule doFireTick false
      RCON_CMDS_FIRST_CONNECT: |-
        /pregen stop
      RCON_CMDS_LAST_DISCONNECT: |-
        /kill @e[type=minecraft:boat]
        /pregen start 200
    ports:
      - "25565:25565"
      - "127.0.0.1:25575:25575"

volumes:
  data: {}