version: '3.8'

services:
  mc:
    image: itzg/minecraft-server:${IMAGE_TAG:-2025.5.1}
    container_name: minecraft-prominence2
    volumes:
      - minecraft_prominence2_data:/data
    environment:
      EULA: "true"
      MOD_PLATFORM: AUTO_CURSEFORGE
      DEBUG: "${DEBUG:-false}"
      CF_API_KEY: ${CF_API_KEY}
      CF_SLUG: prominence-2-rpg
      #CURSEFORGE_FILES: luna, textile-backup, cloth-config, modmenu, fancymenu
      INIT_MEMORY: 8G
      MAX_MEMORY: 24G
      USE_AIKAR_FLAGS: true
      MOTD: Running %MODPACK_NAME% version %env:MODPACK_VERSION%
      LEVEL: prominence2-world
      LEVEL_TYPE: minecraft:large_biomes
      RCON_PASSWORD: ${RCON_PASSWORD}
      CUSTOM_SERVER_PROPERTIES: |-
        allow-flight=true
        spawn-protection=false
      RCON_CMDS_STARTUP:  |-
        /gamerule doFireTick false
        /gamerule mobGriefing false
      #RCON_CMDS_FIRST_CONNECT:
      #RCON_CMDS_LAST_DISCONNECT:
    ports:
      - "25565:25565"
      - "127.0.0.1:25575:25575"
    networks:
      - minecraft_network
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 24G
        reservations:
          memory: 8G
    healthcheck:
      test: ["CMD", "mc-status", "--host", "localhost"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 120s
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    labels:
      - "com.docker.compose.project=games"
      - "com.docker.compose.service=minecraft-prominence2"
    restart: unless-stopped

networks:
  minecraft_network:
    driver: bridge

volumes:
  minecraft_prominence2_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/minecraft-prominence2