services:
  mc:
    image: itzg/minecraft-server:${IMAGE_TAG:-latest}
    volumes:
    - /data/minecraft-steampunk:/data
    - /data/minecraft/modpacks:/modpacks:ro
    environment:
      EULA: "true"
      TYPE: FORGE
      DEBUG: "${DEBUG:-false}"
      VERSION: ${VERSION:-1.19.2}
      FORGE_VERSION: ${FORGE_VERSION:-43.4.0}
      MODPACK: https://mediafilez.forgecdn.net/files/5480/858/SteamPunk_LPS_v24_serverpack.zip
      REMOVE_OLD_MODS: "${REMOVE_OLD_MODS:-false}"
      
    ports:
      - "25565:25565"

volumes:
  data: {}