services:
  mc:
    image: itzg/minecraft-server:${IMAGE_TAG:-latest}
    volumes:
    - data:/data
    - ./modpacks:/modpacks:ro
    environment:
      EULA: "true"
      TYPE: FORGE
      DEBUG: "${DEBUG:-false}"
      VERSION: ${VERSION:-1.19.2}
      FORGE_VERSION: ${FORGE_VERSION:-37.0.90}
      MODPACK: https://www.curseforge.com/minecraft/modpacks/steam-punk/files/5480858
      REMOVE_OLD_MODS: "${REMOVE_OLD_MODS:-false}"
      
    ports:
      - "25565:25565"

volumes:
  data: {}