services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - '80:80'
    environment:
      DEFAULT_HOST: pihole.pixelpaladin.lan
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
    restart: always
