version: '3.8'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.2.1
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    environment:
      DEFAULT_HOST: pihole.pixelpaladin.lan
    volumes:
      # Using a proxy container for docker.sock is more secure
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - 'nginx_certs:/etc/nginx/certs'
      - 'nginx_vhost:/etc/nginx/vhost.d'
      - 'nginx_html:/usr/share/nginx/html'
    networks:
      - web_network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "com.docker.compose.project=networking"
      - "com.docker.compose.service=nginx-proxy"
    restart: unless-stopped

  # Optional: Add Let's Encrypt companion container
  # letsencrypt:
  #   image: nginxproxy/acme-companion:2.2
  #   container_name: nginx-proxy-acme
  #   volumes_from:
  #     - nginx-proxy
  #   volumes:
  #     - '/var/run/docker.sock:/var/run/docker.sock:ro'
  #     - 'acme:/etc/acme.sh'
  #   environment:
  #     DEFAULT_EMAIL: your-email@example.com
  #   depends_on:
  #     - nginx-proxy
  #   restart: unless-stopped

networks:
  web_network:
    driver: bridge

volumes:
  nginx_certs:
    driver: local
  nginx_vhost:
    driver: local
  nginx_html:
    driver: local
  # acme:
  #   driver: local
