version: "3.8"

services:
  palworld:
    image: ripps818/docker-palworld-dedicated-server-wine:latest
    container_name: palworld-server

    restart: unless-stopped
    stop_grace_period: 60s

    ports:
      - "8211:8211/udp"
      - "27015:27015/udp"
      - "8212:8212/tcp"

    environment:
      # Docker
      TZ: America/Vancouver
      PUID: 1000
      PGID: 1000

      # Server
      SERVER_NAME: "SS Palworld"
      SERVER_DESCRIPTION: "SS Palworld Server"

      SERVER_PASSWORD: ${SERVER_PASSWORD}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      PLAYERS: 16

      PORT: 8211
      QUERY_PORT: 27015

      REST_API_ENABLED: "true"
      REST_API_PORT: 8212

      COMMUNITY_SERVER: "false"

      # Keep automatic updates
      UPDATE_ON_BOOT: "true"

    volumes:
      - /data/palworld:/palworld

    networks:
      - game_network

    healthcheck:
      test: ["CMD", "nc", "-uz", "localhost", "8211"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 180s

    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "3"

    labels:
      - "com.docker.compose.project=games"
      - "com.docker.compose.service=palworld"

networks:
  game_network:
    driver: bridge