version: '3.8'

services:
  pihole:
    image: pihole/pihole:${IMAGE_TAG:-latest}
    container_name: pihole
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - "67:67/udp"
      - '8053:80/tcp'
      - '8443:443/tcp'
    volumes:
      - pihole_etc:/etc/pihole
      - pihole_dnsmasq:/etc/dnsmasq.d
      - pihole_certs:/etc/lighttpd/certs
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - CHOWN
    environment:
      FTLCONF_LOCAL_IPV4: 192.168.1.10
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: ${PIHOLE_DOMAIN:-pihole.italicninja.com}
      VIRTUAL_PORT: 80
      TZ: 'America/Vancouver'
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      # Vercel DNS domain (if using Vercel for public DNS)
      PIHOLE_DNS_DOMAIN: ${VERCEL_DOMAIN:-}
      # HTTPS configuration (correct for v6.4.1)
      FTLCONF_WEBSERVER_PORT: '443'
      # DNS configuration
      DNSMASQ_LISTENING: 'all'
      # Upstream DNS servers (Cloudflare by default)
      PIHOLE_DNS_: '1.1.1.1;1.0.0.1'
    extra_hosts:
      # LAN hostnames for other docker containers using nginx-proxy
      - 'pihole pihole.italicninja.com:192.168.1.10'
    networks:
      - dns_network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    healthcheck:
      test: ["CMD", "dig", "@127.0.0.1", "-p", "53", "pi.hole"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "com.docker.compose.project=networking"
      - "com.docker.compose.service=pihole"
    restart: unless-stopped

networks:
  dns_network:
    driver: bridge
    name: dns_network

volumes:
  pihole_etc:
    driver: local
  pihole_dnsmasq:
    driver: local
  pihole_certs:
    driver: local
