version: '3.8'

services:
  pihole:
    image: pihole/pihole:2023.05.2
    container_name: pihole
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - "67:67/udp"
      - '8053:80/tcp'
    volumes:
      - pihole_etc:/etc/pihole
      - pihole_dnsmasq:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    environment:
      FTLCONF_LOCAL_IPV4: 192.168.1.10
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: pihole.pixelpaladin.lan
      VIRTUAL_PORT: 80
      TZ: 'America/Vancouver'
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      # FTLCONF_webserver_api_password: ${webserver_api_password}
    extra_hosts:
      # LAN hostnames for other docker containers using nginx-proxy
      - 'pihole pihole.pixelpaladin.lan:192.168.1.10'
    networks:
      - dns_network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    healthcheck:
      test: ["CMD", "dig", "@127.0.0.1", "-p", "53", "pi.hole"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "com.docker.compose.project=networking"
      - "com.docker.compose.service=pihole"
    restart: unless-stopped

networks:
  dns_network:
    driver: bridge

volumes:
  pihole_etc:
    driver: local
  pihole_dnsmasq:
    driver: local
