version: '3'

services:
  valheim-server:
    image: lloesche/valheim-server
    container_name: valheim-server
    cap_add:
      - SYS_NICE
    stop_grace_period: 120s
    ports:
      - "2456-2457:2456-2457/udp"
    volumes:
      - /data/valheim-server/config:/config
      - /data/valheim-server/data:/opt/valheim
      - /backup/valheim:/backup/valheim
    environment:
      - SERVER_NAME=SSFriendshipFrostholm
      - WORLD_NAME=Frostholm
      - SERVER_PASS=${SERVER_PASS}
      - BACKUPS=true
      - BACKUPS_CRON=0 */2 * * *
      - BACKUPS_DIRECTORY=/config/backups
      - BACKUPS_MAX_AGE=7
      - BACKUPS_MAX_COUNT=10
      - BACKUPS_IF_IDLE=true
      - POST_BACKUP_HOOK=cp @BACKUP_FILE@ /backup/valheim/$(basename @BACKUP_FILE@)
      - BEPINEX=true
      - 'POST_BEPINEX_CONFIG_HOOK=curl -sfSL https://thunderstore.io/package/download/Searica/Extra_Snap_Points_Made_Easy/2.0.5/ -o /tmp/extra_snap_points.zip && unzip -o /tmp/extra_snap_points.zip -d /tmp/extra_snap_points && cp /tmp/extra_snap_points/*.dll /config/bepinex/plugins/ && rm -rf /tmp/extra_snap_points*'
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK}
      - DISCORD_AVATAR_URL=https://cdn.cloudflare.steamstatic.com/steam/apps/892970/header.jpg
      - SERVER_IP=${SERVER_IP:-your-server-ip}
      - MAX_PLAYERS=10
      - 'DISCORD_EMBED_STARTUP={"username":"Valheim Server","avatar_url":"DISCORD_AVATAR_URL_PLACEHOLDER","embeds":[{"title":"🚀 Server Starting","description":"**SERVER_NAME_PLACEHOLDER** is initializing...","color":1973162,"thumbnail":{"url":"DISCORD_AVATAR_URL_PLACEHOLDER"},"fields":[{"name":"🌍 World","value":"WORLD_NAME_PLACEHOLDER","inline":true},{"name":"🌐 Server Address","value":"SERVER_IP_PLACEHOLDER:2456","inline":true},{"name":"👥 Max Players","value":"MAX_PLAYERS_PLACEHOLDER","inline":true},{"name":"🔧 Mods","value":"BepInEx + Extra Snap Points","inline":true},{"name":"💾 Backups","value":"Every 2 hours","inline":true},{"name":"⏱️ Estimated Startup","value":"~2-3 minutes","inline":true}],"footer":{"text":"Server Status: Initializing","icon_url":"https://cdn.discordapp.com/emojis/loading.gif"},"timestamp":"TIMESTAMP_PLACEHOLDER"}]}'
      - 'PRE_BOOTSTRAP_HOOK=EMBED_JSON="$$DISCORD_EMBED_STARTUP"; EMBED_JSON=$$(echo "$$EMBED_JSON" | sed "s|DISCORD_AVATAR_URL_PLACEHOLDER|$$DISCORD_AVATAR_URL|g" | sed "s|SERVER_NAME_PLACEHOLDER|$$SERVER_NAME|g" | sed "s|WORLD_NAME_PLACEHOLDER|$$WORLD_NAME|g" | sed "s|SERVER_IP_PLACEHOLDER|$$SERVER_IP|g" | sed "s|MAX_PLAYERS_PLACEHOLDER|$$MAX_PLAYERS|g" | sed "s|TIMESTAMP_PLACEHOLDER|$$(date -u +%Y-%m-%dT%H:%M:%S.000Z)|g"); curl -sfSL -X POST -H "Content-Type: application/json" -d "$$EMBED_JSON" "$$DISCORD_WEBHOOK"'
    restart: unless-stopped
