version: '3'

services:
  valheim-server:
    image: lloesche/valheim-server
    container_name: valheim-server
    cap_add:
      - SYS_NICE
    stop_grace_period: 120s
    ports:
      - "2456-2457:2456-2457/udp"
    volumes:
      - valheimdata/config:/config
      - valheimdata/data:/opt/valheim
    environment:
      - SERVER_NAME=SSFriendshipFrostholm
      - WORLD_NAME=Frostholm
      - SERVER_PASS=${SERVER_PASS}
      - POST_BACKUP_HOOK='timeout 300 scp @BACKUP_FILE@ /backup/valheim/$(basename @BACKUP_FILE@)'
    restart: unless-stopped

volumes:
  valheimdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/data/valheim-server'