version: '3'

services:
  valheim-server:
    image: lloesche/valheim-server
    container_name: valheim-server
    cap_add:
      - SYS_NICE
    stop_grace_period: 120s
    ports:
      - "2456-2457:2456-2457/udp"
    volumes:
      - /data/valheim-server/config:/config
      - /data/valheim-server/data:/opt/valheim
      - /backup/valheim:/backup/valheim
    environment:
      - SERVER_NAME=SSFriendshipFrostholm
      - WORLD_NAME=Frostholm
      - SERVER_PASS=${SERVER_PASS}
      - BACKUPS=true
      - BACKUPS_CRON=0 */2 * * *
      - BACKUPS_DIRECTORY=/config/backups
      - BACKUPS_MAX_AGE=7
      - BACKUPS_MAX_COUNT=10
      - BACKUPS_IF_IDLE=true
      - POST_BACKUP_HOOK=cp @BACKUP_FILE@ /backup/valheim/$(basename @BACKUP_FILE@)
      - BEPINEX=true
      - 'POST_BEPINEX_CONFIG_HOOK=curl -sfSL https://thunderstore.io/package/download/Searica/Extra_Snap_Points_Made_Easy/2.0.5/ -o /tmp/extra_snap_points.zip && unzip -o /tmp/extra_snap_points.zip -d /tmp/extra_snap_points && cp -r /tmp/extra_snap_points/BepInExPack_Valheim/* /config/bepinex/ && cp -r /tmp/extra_snap_points/plugins/* /config/bepinex/plugins/ && rm -rf /tmp/extra_snap_points*'
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK}
      - DISCORD_MESSAGE=Starting Valheim server $$SERVER_NAME
      - 'PRE_BOOTSTRAP_HOOK=curl -sfSL -X POST -H "Content-Type: application/json" -d "{\"username\":\"Valheim\",\"content\":\"$$(eval echo $$DISCORD_MESSAGE)\"}" "$$DISCORD_WEBHOOK"'
    restart: unless-stopped
