version: '3.8'

services:
  vercel-ddns:
    image: alpine:3.18
    container_name: vercel-ddns
    environment:
      # Vercel API Configuration
      VERCEL_TOKEN: ${VERCEL_TOKEN}
      VERCEL_DOMAIN: ${VERCEL_DOMAIN}
      VERCEL_RECORD_NAME: ${VERCEL_RECORD_NAME:-@}
      VERCEL_RECORD_TYPE: ${VERCEL_RECORD_TYPE:-A}
      
      # Check interval in seconds (300 = 5 minutes)
      CHECK_INTERVAL: ${CHECK_INTERVAL:-300}
      
      # Optional: Set timezone
      TZ: ${TZ:-UTC}
    volumes:
      - './scripts/vercel-ddns.sh:/tmp/vercel-ddns.sh:ro'
      - 'ddns_data:/app/data'
    command: >
      sh -c "
        apk add --no-cache curl jq &&
        cp /tmp/vercel-ddns.sh /app/vercel-ddns.sh &&
        chmod +x /app/vercel-ddns.sh &&
        /app/vercel-ddns.sh
      "
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
        reservations:
          cpus: '0.05'
          memory: 32M
    healthcheck:
      test: ["CMD", "pgrep", "-f", "vercel-ddns.sh"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "com.docker.compose.project=networking"
      - "com.docker.compose.service=vercel-ddns"
    restart: unless-stopped
    networks:
      - ddns_network

networks:
  ddns_network:
    driver: bridge

volumes:
  ddns_data:
    driver: local