version: '3.8'

services:
  zomboid-server:
    image: danixu86/project-zomboid-dedicated-server:latest-release
    container_name: zomboid-server
    ports:
      - "16261:16261/udp"
      - "16262:16262/udp"
      - "8766:8766/udp"
      - "8767:8767/udp"
      - "27015:27015/tcp"
    volumes:
      - zomboid_config:/home/steam/Zomboid
      - zomboid_server:/home/steam/pz-dedicated
    environment:
      # Build 42 Support
      - STEAMAPPBRANCH=unstable
      
      # Admin Configuration
      - ADMINUSERNAME=${ZOMBOID_ADMIN_USERNAME:-admin}
      - ADMINPASSWORD=${ZOMBOID_ADMIN_PASSWORD}
      
      # Server Configuration
      - SERVERNAME=${ZOMBOID_SERVER_NAME:-SSF-HordeNight}
      - DISPLAYNAME=SSF - Horde Night
      - PASSWORD=${ZOMBOID_SERVER_PASSWORD:-}
      - RCONPASSWORD=${ZOMBOID_RCON_PASSWORD}
      
      # Server Settings
      - PUBLIC=true
      - STEAMVAC=true
      - SERVERPRESET=Apocalypse
      - PORT=16261
      - MEMORY=${ZOMBOID_MEMORY:-6144m}
      
      # Workshop Mods (semicolon-separated)
      # REMOVED (Steam Workshop policy violations):
      # 3586053117 - Common Sense B42 Patch
      # 2544353492 - Has Been Read
      # 2335368829 - Authentic Z (also caused server crash)
      # 2553809727 - KillCount
      # 3450258411 = SHELTER Echo Creek B42 (map mod)
      - WORKSHOP_IDS=2875848298;2447729538;2625625421;3171167894;2950902979;2684285534;2714198296;2866258937;2972289937;3618557184;3413150945;3330403100;2940354599;3564950449;3624308198;3429294706;3490188370;3508537032;3437629766;3617854007;2840805724;3110911330;3615459796;3433203442;3543229299;3638469608;2286124931;3539876164;3610677934;3465040406;3461263912;3395171770;3390174394;3623247107;2909035179;3627539752;3623609320;3430172149;3450258411
      # For Build 42, MOD_IDS require \\ prefix (load order matters!)
      # Removed (workshop violations): CommonSenseEarlyPatch, CommonSenseLatePatch, P4HasBeenRead, Authentic Z - Current, KillCount
      # Added: shelter-EC42 for Echo Creek map spawning
      - MOD_IDS=\\NeatUI_Framework;\\ProximityInventory4213;\\FWOFitnessWorkoutOverhaul;\\FWOBenchPress&Treadmill;\\KI5trailers;\\MoreDamagedObjects;\\HereGoesTheSun;\\GenRange;\\MiniHealthPanel;\\NoLighterNeeded;\\SpnCloth;\\EQUIPMENT_UI;\\damnlib;\\isoContainers;\\FH;\\BB_CommonSense;\\CSB42MP;\\ProjectSummerCar;\\Homebound;\\Project_Cook;\\CleanUI;\\ArcheryNexus;\\SimpleOverhaulTraitsAndOccupations;\\WoodysRainAndWetSnowCleaning;\\87fordB700;\\B42_TMC_Trolley;\\PROJECTRVInterior42;\\ReadFasterWhenSitting42MpFix;\\CombatText;\\GymEquipment;\\HBVCEFb42;\\OpenAllContainers;\\CleanHotBar;\\moodlesinlua;\\devcattmoodles;\\MultiplayerPause_FastForward;\\BetterCarPhysics;\\twistmapimprovements;\\flipvehicleplustrailer;\\shelter-EC42
      
      # Performance & Updates
      - FORCEUPDATE=false
      
      # Localization
      - LANG=en_EN.UTF-8
      - TZ=${TZ:-UTC}
    networks:
      - game_network
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 8G
        reservations:
          memory: 6G
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f ProjectZomboid64 || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 300s
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    labels:
      - "com.docker.compose.project=games"
      - "com.docker.compose.service=zomboid"
    restart: unless-stopped

networks:
  game_network:
    driver: bridge

volumes:
  zomboid_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/ZomboidConfig
  zomboid_server:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/ZomboidDedicatedServer
