version: '3.8'

services:
  zomboid-server:
    image: danixu86/project-zomboid-dedicated-server:latest
    container_name: zomboid-server
    ports:
      - "16261:16261/udp"
      - "16262:16262/udp"
      - "8766:8766/udp"
      - "8767:8767/udp"
      - "27015:27015/tcp"
    volumes:
      - zomboid_config:/home/steam/Zomboid
      - zomboid_server:/home/steam/pz-dedicated
    environment:
      # Stable Build
      - STEAMAPPBRANCH=public
      - STEAMAPPVALIDATE=true
      
      # Admin Configuration
      - ADMINUSERNAME=${ZOMBOID_ADMIN_USERNAME:-admin}
      - ADMINPASSWORD=${ZOMBOID_ADMIN_PASSWORD:-changeme}
      
      # Server Configuration
      - SERVERNAME=${ZOMBOID_SERVER_NAME:-SSF-HordeNight}
      - DISPLAYNAME=SSF - Horde Night
      - PASSWORD=${ZOMBOID_SERVER_PASSWORD:-}
      - RCONPASSWORD=${ZOMBOID_RCON_PASSWORD}
      
      # Server Settings
      - PUBLIC=true
      - STEAMVAC=true
      - SERVERPRESET=Apocalypse
      - PORT=16261
      - MEMORY=${ZOMBOID_MEMORY:-6144m}
      
      # Workshop Mods (disabled)
      - WORKSHOP_IDS=""
      - MOD_IDS=""

      # Performance & Updates
      - FORCEUPDATE=false
      - FORCESTEAMCLIENTSOUPDATE=false
      
      # Localization
      - LANG=en_EN.UTF-8
      - TZ=America/Vancouver
    networks:
      - game_network
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 8G
        reservations:
          memory: 6G
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f ProjectZomboid64 || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 300s
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    labels:
      - "com.docker.compose.project=games"
      - "com.docker.compose.service=zomboid"
    restart: unless-stopped

networks:
  game_network:
    driver: bridge

volumes:
  zomboid_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/ZomboidConfig
  zomboid_server:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/ZomboidDedicatedServer
